import type { Gotcha, Lang } from "../types";

/**
 * Language-specific traps, weighted toward the ones that generated code lands on
 * repeatedly. Each is a thing to *check for*, not a style opinion: every entry
 * changes behaviour.
 */
export const GOTCHAS: Gotcha[] = [
  /* --------------------------------- Python --------------------------------- */
  {
    id: "py-mutable-default",
    lang: "Python",
    family: "state",
    title: "Mutable default argument",
    body: "The default is evaluated once, at definition time, and shared by every call for the life of the process. The second call sees the first call's data.",
    code: "def add_item(item, items=[]):\n    items.append(item)\n    return items",
    fix: "def add_item(item, items=None):\n    if items is None:\n        items = []",
  },
  {
    id: "py-utcnow",
    lang: "Python",
    family: "time",
    title: "datetime.utcnow() returns a naive datetime",
    body: "It represents UTC but carries no tzinfo. Compared against an aware value it raises TypeError; compared against a naive local value it silently succeeds and is wrong by the offset. Deprecated since 3.12 for exactly this reason.",
    fix: "datetime.now(timezone.utc)",
  },
  {
    id: "py-dollar-newline",
    lang: "Python",
    family: "boundary",
    title: "$ matches before a trailing newline",
    body: 'In Python\'s re, `$` matches at the end of the string *or* just before a final newline. So "ok@example.com\\nevil@bank.com" passes a `^...$` validator. Anywhere the value reaches a header or an SMTP envelope, that is an injection vector.',
    fix: "re.fullmatch(pattern, s), or anchor with \\A and \\Z",
  },
  {
    id: "py-late-binding",
    lang: "Python",
    family: "state",
    title: "Closures capture the variable, not its value",
    body: "Every lambda in the list below returns 2, because they all close over the same `i` and read it after the loop has finished. Generated code hits this in callback registration and in retry-handler construction.",
    code: "fns = [lambda: i for i in range(3)]\n# all three return 2",
    fix: "lambda i=i: i — or use functools.partial",
  },
  {
    id: "py-round-banker",
    lang: "Python",
    family: "coercion",
    title: "round() uses banker's rounding",
    body: "round(0.5) is 0 and round(2.5) is 2 — ties go to the even number, not up. Any code that reimplements a currency rounding rule from a spec written by an accountant will disagree with the spec at exactly the .5 cases.",
    fix: "Decimal(x).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)",
  },
  {
    id: "py-float-money",
    lang: "Python",
    family: "coercion",
    title: "Floats for money",
    body: "0.1 + 0.2 != 0.3. Errors accumulate across a basket and the total disagrees with hand arithmetic by cents that nobody can trace.",
    fix: "decimal.Decimal, or integer cents",
  },
  {
    id: "py-mutate-iterate",
    lang: "Python",
    family: "state",
    title: "Mutating a dict or set while iterating it",
    body: "RuntimeError: dictionary changed size during iteration. It only fires when the branch that deletes is actually taken, so a test with no stale entries passes cleanly and it detonates in production.",
    fix: "Iterate a snapshot: for k in list(d)",
  },
  {
    id: "py-shallow-copy",
    lang: "Python",
    family: "state",
    title: ".copy() and dict(x) and list(x) are all shallow",
    body: "The outer container is new; every nested container is the same object. A caller that mutates the result at depth 2 mutates the original.",
    fix: "copy.deepcopy, or document the sharing",
  },
  {
    id: "py-is-vs-eq",
    lang: "Python",
    family: "coercion",
    title: "`is` compares identity, and small ints are interned",
    body: "`x is 256` is True and `x is 257` is False for the same construction, because CPython caches small integers. Code that uses `is` for equality works during development and fails on the first value outside the cache.",
    fix: "Use == for values; reserve `is` for None, True, False and sentinels",
  },
  {
    id: "py-open-encoding",
    lang: "Python",
    family: "coercion",
    title: "open() without an encoding uses a platform default",
    body: "The default is locale-dependent, so the same file parses on the developer's machine and raises UnicodeDecodeError in the container. Silent corruption is also possible when the bytes happen to decode.",
    fix: 'open(path, encoding="utf-8")',
  },
  {
    id: "py-except-broad",
    lang: "Python",
    family: "failure",
    title: "except Exception catches your own bugs",
    body: "A NameError or an AttributeError inside the try is caught, retried, and reported as an upstream failure. It also catches the deterministic errors that retrying can never fix, such as a response body that is not JSON.",
    fix: "Catch only the exception types you intend to handle",
  },

  /* ------------------------------- JavaScript ------------------------------- */
  {
    id: "js-sort-lexicographic",
    lang: "JavaScript",
    family: "coercion",
    title: "Default sort compares as strings",
    body: "[10, 9, 100].sort() gives [10, 100, 9]. Wrong for any numeric data spanning digit counts, which for latencies, prices and counts is all of it. Returns a plausible array; never throws.",
    fix: "arr.sort((a, b) => a - b)",
  },
  {
    id: "js-sort-in-place",
    lang: "JavaScript",
    family: "state",
    title: "sort(), reverse() and splice() mutate in place",
    body: "`const sorted = times.sort()` is not a copy — it is the same array under a new name, and the name is the only thing suggesting otherwise. The caller's array is silently reordered.",
    fix: "[...arr].sort(...), or toSorted() where available",
  },
  {
    id: "js-fetch-ok",
    lang: "JavaScript",
    family: "failure",
    title: "fetch does not reject on 4xx or 5xx",
    body: "A 500 is a *resolved* promise with ok === false. Calling .json() on the HTML error page throws inside the then-chain, and with no .catch it becomes an unhandled rejection that nothing surfaces.",
    fix: "if (!res.ok) throw new Error(res.status)",
  },
  {
    id: "js-truthiness",
    lang: "JavaScript",
    family: "coercion",
    title: "0, \"\", NaN, null and undefined are all falsy",
    body: "`if (count)` skips a legitimate zero. `if (name)` skips a legitimate empty string. `if (cached)` skips a legitimately cached null — which is the case an attacker can generate at will.",
    fix: "Test what you mean: `if (count > 0)`, `if (x != null)`, `cache.has(key)`",
  },
  {
    id: "js-nullish",
    lang: "JavaScript",
    family: "coercion",
    title: "|| replaces valid falsy values; ?? does not",
    body: "`const limit = opts.limit || 20` turns an explicit 0 into 20. This is the single most common config bug in generated JavaScript, and it looks completely idiomatic.",
    fix: "const limit = opts.limit ?? 20",
  },
  {
    id: "js-float",
    lang: "JavaScript",
    family: "coercion",
    title: "All numbers are doubles",
    body: "0.1 + 0.2 === 0.30000000000000004, and integers above 2^53 lose precision — which includes many database ids and Twitter-style snowflake ids arriving as JSON numbers.",
    fix: "Integer cents for money; strings or BigInt for large ids",
  },
  {
    id: "js-date-months",
    lang: "JavaScript",
    family: "contract",
    title: "Date months are 0-indexed and days are not",
    body: "new Date(2026, 1, 15) is 15 February. Worse, out-of-range values roll over silently: new Date(2026, 12, 1) is January 2027 rather than an error.",
    fix: "Use a date library, or be explicit and test the boundaries",
  },
  {
    id: "js-nan",
    lang: "JavaScript",
    family: "coercion",
    title: "NaN is not equal to itself, and it propagates",
    body: "NaN === NaN is false, so an equality check never detects it. Any arithmetic involving it yields NaN, so one bad value silently poisons every downstream number in a dashboard.",
    fix: "Number.isNaN(x); validate at the boundary rather than downstream",
  },
  {
    id: "js-array-holes",
    lang: "JavaScript",
    family: "boundary",
    title: "Array(n) creates holes that map and forEach skip",
    body: "Array(5).map((_, i) => i) returns five holes, not [0,1,2,3,4]. The code looks like an idiomatic range and produces nothing.",
    fix: "Array.from({ length: 5 }, (_, i) => i)",
  },
  {
    id: "js-async-foreach",
    lang: "JavaScript",
    family: "time",
    title: "forEach does not await",
    body: "`items.forEach(async i => await save(i))` returns immediately with every save still in flight. The function that contains it resolves before any write has landed, so the caller proceeds on a state that does not exist yet.",
    fix: "for (const i of items) { await save(i) } — or await Promise.all(items.map(...))",
  },

  /* ------------------------------- TypeScript ------------------------------- */
  {
    id: "ts-erased",
    lang: "TypeScript",
    family: "contract",
    title: "Types are erased; they do not validate anything",
    body: "`const user = await res.json() as User` performs no check at all. If the API changed, you have a User-shaped lie that fails much later, at a property access in the view layer, with this line nowhere in the stack.",
    fix: "Parse at the boundary with zod/valibot, or hand-write a type guard",
  },
  {
    id: "ts-non-null",
    lang: "TypeScript",
    family: "failure",
    title: "The ! operator silences a real possibility",
    body: "`user!.email` tells the compiler to stop objecting; it does not make user non-null. Every `!` in generated code marks a place where the model could not prove something and asserted it instead.",
    fix: "Narrow with an explicit check, and decide what the null case should do",
  },
  {
    id: "ts-any-leak",
    lang: "TypeScript",
    family: "contract",
    title: "any spreads silently through the call graph",
    body: "One untyped third-party function returning any infects every value derived from it, and no error is reported anywhere along the chain. Caches, JSON.parse and older @types packages are the usual sources.",
    fix: "noImplicitAny plus unknown at boundaries, so the cast has to be deliberate",
  },
  {
    id: "ts-index-access",
    lang: "TypeScript",
    family: "boundary",
    title: "arr[i] is typed as T, not T | undefined",
    body: "By default indexing is not checked, so `arr[10].name` type-checks on a three-element array and throws at runtime. The same applies to Record lookups on a key that is absent.",
    fix: "Enable noUncheckedIndexedAccess",
  },
  {
    id: "ts-structural",
    lang: "TypeScript",
    family: "contract",
    title: "Structural typing lets extra properties through",
    body: "Excess-property checking only applies to object literals assigned directly. A variable with additional fields satisfies a narrower type, so data you did not intend to forward — including secrets — passes into functions and out over the wire.",
    fix: "Pick explicitly rather than passing whole objects through",
  },
  {
    id: "ts-enum-numeric",
    lang: "TypeScript",
    family: "coercion",
    title: "Numeric enums accept any number",
    body: "A numeric enum has a reverse mapping and its type accepts arbitrary numbers, so an invalid value from JSON is assignable to the enum type and then fails no check anywhere.",
    fix: "String enums, or a union of string literals",
  },

  /* ----------------------------------- SQL ---------------------------------- */
  {
    id: "sql-left-join-where",
    lang: "SQL",
    family: "contract",
    title: "A WHERE on the right table turns LEFT JOIN into INNER JOIN",
    body: "The NULL-filled rows a LEFT JOIN produces fail any WHERE predicate on the right table, because NULL >= x is NULL, which is not true. The rows the join existed to preserve are exactly the rows removed.",
    fix: "Move the predicate into the ON clause",
  },
  {
    id: "sql-null-compare",
    lang: "SQL",
    family: "coercion",
    title: "Nothing equals NULL, including NULL",
    body: "`WHERE status = NULL` returns no rows and no error. `WHERE status != 'done'` also excludes every row where status is NULL, which is almost never what was meant.",
    fix: "IS NULL / IS NOT NULL, and COALESCE in the comparison when NULLs are meaningful",
  },
  {
    id: "sql-not-in-null",
    lang: "SQL",
    family: "coercion",
    title: "NOT IN with a NULL in the list returns nothing",
    body: "If the subquery yields a single NULL, `x NOT IN (subquery)` is NULL for every row and the result set is empty. The query is valid, runs fast, and silently answers 'none'.",
    fix: "NOT EXISTS, or filter NULLs out of the subquery",
  },
  {
    id: "sql-count-col",
    lang: "SQL",
    family: "boundary",
    title: "COUNT(col) skips NULLs; COUNT(*) does not",
    body: "In a LEFT JOIN aggregate this is usually what you want — but swapping one for the other changes every zero into a one, or vice versa, and both queries look correct.",
    fix: "Be deliberate; COUNT(o.id) for 'orders', COUNT(*) for 'rows'",
  },
  {
    id: "sql-between-timestamps",
    lang: "SQL",
    family: "boundary",
    title: "BETWEEN is inclusive at both ends",
    body: "`created_at BETWEEN '2026-01-01' AND '2026-01-31'` excludes almost all of the 31st, because the literal coerces to midnight. Chained monthly reports then double-count or drop the boundary day.",
    fix: ">= start AND < next_start",
  },
  {
    id: "sql-implicit-cast",
    lang: "SQL",
    family: "coercion",
    title: "An implicit cast disables the index",
    body: "Comparing a varchar column against a number, or applying a function to the column side of a predicate, forces a full scan. The query is correct and a hundred times slower, which surfaces only at production data volume.",
    fix: "Match the types, and keep functions off the indexed column",
  },
  {
    id: "sql-distinct-mask",
    lang: "SQL",
    family: "contract",
    title: "DISTINCT hiding a join fan-out",
    body: "A DISTINCT added to make duplicates go away usually means a join multiplied rows. The duplicates are gone; any SUM or COUNT in the same query is still multiplied.",
    fix: "Fix the join, or aggregate in a subquery before joining",
  },
  {
    id: "sql-string-concat",
    lang: "SQL",
    family: "failure",
    title: "String-built queries",
    body: "Any query assembled by concatenation is an injection unless every input is provably not attacker-controlled — and that proof does not survive refactoring. Generated code reaches for f-strings because they are shorter.",
    fix: "Parameterised queries, always, including for the 'safe' internal ones",
  },

  /* ----------------------------------- Rust --------------------------------- */
  {
    id: "rs-overflow",
    lang: "Rust",
    family: "boundary",
    title: "Integer overflow panics in debug and wraps in release",
    body: "The same arithmetic aborts under `cargo test` and silently wraps in the shipped binary. A test suite therefore cannot tell you what production does.",
    fix: "checked_add / saturating_add / wrapping_add — state the intent",
  },
  {
    id: "rs-as-cast",
    lang: "Rust",
    family: "coercion",
    title: "`as` truncates without complaint",
    body: "`300u32 as u8` is 44. `1e10 as i32` saturates. `-1i32 as u32` is 4294967295. None of these warn, and `as` is the shortest way to make a type error go away, so generated code reaches for it.",
    fix: "TryFrom / try_into and handle the error",
  },
  {
    id: "rs-partial-cmp-unwrap",
    lang: "Rust",
    family: "failure",
    title: "sort_by(partial_cmp().unwrap()) panics on NaN",
    body: "Floats are only partially ordered, so partial_cmp returns None for NaN and the unwrap aborts. It is the idiomatic-looking way to sort floats and it is a crash waiting for one bad input.",
    fix: "sort_by(|a, b| a.total_cmp(b))",
  },
  {
    id: "rs-unwrap-lib",
    lang: "Rust",
    family: "failure",
    title: "unwrap() and expect() in library code",
    body: "They convert a recoverable error into a process abort at a point where the caller had every ability to handle it. Generated code uses them to satisfy the type checker rather than because the invariant holds.",
    fix: "Return Result and let the caller decide",
  },
  {
    id: "rs-clone-semantics",
    lang: "Rust",
    family: "state",
    title: "clone() to satisfy the borrow checker changes the semantics",
    body: "The borrow error said two places wanted the same value. Cloning makes two independent values, so a mutation through one is invisible to the other — which compiles, and is a different program.",
    fix: "Restructure the borrow, or use Rc<RefCell<_>> / Arc<Mutex<_>> if sharing was intended",
  },
  {
    id: "rs-guard-await",
    lang: "Rust",
    family: "time",
    title: "Holding a std Mutex guard across an .await",
    body: "The guard is held while the task is suspended, so another task on the same thread that wants the lock deadlocks. It compiles only because the future is not Send, which produces an error far from the cause.",
    fix: "Drop the guard before awaiting, or use tokio::sync::Mutex",
  },
  {
    id: "rs-seed-accumulator",
    lang: "Rust",
    family: "boundary",
    title: "Accumulators seeded with a possible answer",
    body: "`let mut max = 0.0` returns 0.0 for all-negative input and for empty input — a value not present in the data, indistinguishable from a real result.",
    fix: "fold over the first element, or use .iter().copied().reduce(f64::max) returning Option",
  },

  /* ------------------------------------ Go ---------------------------------- */
  {
    id: "go-loopvar",
    lang: "Go",
    family: "state",
    title: "Loop-variable capture, before Go 1.22",
    body: "A goroutine closing over the range variable shares it with every other iteration on Go 1.21 and earlier, so most of them read the final value. Go 1.22 made the variable per-iteration — so the same source is correct or broken depending on the `go` directive in go.mod.",
    fix: "Pass it as a parameter: go func(u string) { ... }(u)",
  },
  {
    id: "go-nil-interface",
    lang: "Go",
    family: "coercion",
    title: "A nil pointer in an interface is not a nil interface",
    body: "Returning a nil *MyError as an error gives a non-nil interface holding a nil pointer, so `if err != nil` is true and the caller reports a failure that did not happen.",
    fix: "Return a bare nil, not a typed nil variable",
  },
  {
    id: "go-map-concurrent",
    lang: "Go",
    family: "state",
    title: "Concurrent map writes are a fatal error",
    body: "Not a panic — a fatal error. recover() cannot catch it and deferred cleanup does not run; the process dies. It is probabilistic, so small inputs pass review and CI.",
    fix: "sync.Mutex, sync.Map, or a single owning goroutine fed by a channel",
  },
  {
    id: "go-defer-loop",
    lang: "Go",
    family: "boundary",
    title: "defer runs at function exit, not at the end of the loop body",
    body: "`defer f.Close()` inside a loop over ten thousand files holds every handle until the function returns. It looks like correct cleanup and it is a descriptor leak.",
    fix: "Wrap the body in its own function, or close explicitly",
  },
  {
    id: "go-slice-alias",
    lang: "Go",
    family: "state",
    title: "Slices share a backing array, and append sometimes copies",
    body: "`b := a[:2]; b = append(b, x)` overwrites a[2] when capacity allows and silently does not when it reallocates. Whether the caller sees the write depends on capacity, which nothing in the code states.",
    fix: "Copy explicitly, or use a full slice expression a[:2:2] to force reallocation",
  },
  {
    id: "go-http-timeout",
    lang: "Go",
    family: "time",
    title: "http.DefaultClient has no timeout",
    body: "http.Get on an unresponsive server waits forever, holding a goroutine and a connection. Any WaitGroup behind it never returns and the whole call hangs with no error.",
    fix: "&http.Client{Timeout: ...}, plus http.NewRequestWithContext",
  },
  {
    id: "go-err-ignored",
    lang: "Go",
    family: "failure",
    title: "Errors dropped with _ or an early return",
    body: "A goroutine that returns on error leaves the key simply absent from the result, indistinguishable from an input that was never supplied. Unchecked Close() on a writer discards the flush error, which is where the data loss lives.",
    fix: "Carry a per-item result with either a value or an error",
  },
  {
    id: "go-map-order",
    lang: "Go",
    family: "contract",
    title: "Map iteration order is deliberately randomised",
    body: "Code that produces output from a map range is non-deterministic between runs. Tests that happen to pass once will fail later, and serialised output differs run to run.",
    fix: "Collect the keys, sort them, then range over the sorted slice",
  },

  /* ----------------------------------- Java --------------------------------- */
  {
    id: "java-round-long",
    lang: "Java",
    family: "coercion",
    title: "Math.round returns a long, so the next division is integer",
    body: "Math.round(x * 100) / 100 truncates to whole units and then widens back to double on return. 19.99 becomes 19.0 with no warning anywhere.",
    fix: "Divide by 100.0 — or better, use BigDecimal",
  },
  {
    id: "java-integer-cache",
    lang: "Java",
    family: "coercion",
    title: "== on boxed Integers works up to 127",
    body: "Integer.valueOf caches -128..127, so reference comparison succeeds for small values and fails above them. Code tested with small ids works and breaks on real ones.",
    fix: ".equals(), or unbox to int",
  },
  {
    id: "java-int-div",
    lang: "Java",
    family: "coercion",
    title: "Integer division truncates toward zero",
    body: "`(a + b) / 2` on ints, or `count / total * 100` for a percentage, yields 0 for every case where the true answer is a fraction. The expression reads as arithmetic and behaves as floor division.",
    fix: "Cast one operand to double, or reorder to multiply first",
  },
  {
    id: "java-equals-hashcode",
    lang: "Java",
    family: "contract",
    title: "equals without hashCode",
    body: "Two objects that are equal but hash differently land in different buckets, so a HashMap lookup misses and a HashSet holds duplicates. Nothing raises; the collection is just quietly wrong.",
    fix: "Override both, or use a record",
  },
  {
    id: "java-mutable-key",
    lang: "Java",
    family: "state",
    title: "Mutating an object used as a map key",
    body: "The hash changes, the entry stays in its old bucket, and it becomes unreachable — get returns null for a key the map visibly contains.",
    fix: "Immutable keys only",
  },
  {
    id: "java-aslist",
    lang: "Java",
    family: "boundary",
    title: "Arrays.asList and List.of are not ArrayLists",
    body: "Arrays.asList is fixed-size, so add throws UnsupportedOperationException. List.of is fully immutable and additionally rejects null elements with NullPointerException.",
    fix: "new ArrayList<>(List.of(...)) when the result must be mutable",
  },
  {
    id: "java-sdf",
    lang: "Java",
    family: "time",
    title: "SimpleDateFormat is not thread-safe",
    body: "A static instance shared across request threads produces corrupted or wildly wrong dates under concurrency, intermittently, with no exception. It is still the first thing most training data reaches for.",
    fix: "java.time.DateTimeFormatter, which is immutable and thread-safe",
  },
  {
    id: "java-swallow",
    lang: "Java",
    family: "failure",
    title: "catch (Exception e) { e.printStackTrace(); }",
    body: "Execution continues on a state the failed operation never established, and the trace goes to stderr where no log aggregator will find it. The method returns a value that means nothing.",
    fix: "Log with context at the right level and rethrow, or handle it properly",
  },

  /* ------------------------------------ C# ---------------------------------- */
  {
    id: "cs-deferred",
    lang: "C#",
    family: "time",
    title: "LINQ is deferred and can be enumerated twice",
    body: "Where() executes nothing. A Count() inside a log line runs the whole query, and returning the sequence runs it again in the caller — two round trips, or, on a one-shot sequence, a correct count and an empty result.",
    fix: "Materialise once with ToList()",
  },
  {
    id: "cs-context-disposed",
    lang: "C#",
    family: "failure",
    title: "A deferred query outliving its DbContext",
    body: "Returning IEnumerable from a scoped service means the query runs wherever the caller iterates — potentially after disposal, throwing ObjectDisposedException from a stack frame unrelated to the cause.",
    fix: "Materialise before returning, or make the lifetime contract explicit",
  },
  {
    id: "cs-async-void",
    lang: "C#",
    family: "failure",
    title: "async void cannot be awaited and its exceptions are unobservable",
    body: "An exception thrown inside an async void method is raised on the synchronization context and typically crashes the process rather than propagating to a caller who could handle it.",
    fix: "async Task, except for genuine event handlers",
  },
  {
    id: "cs-result-deadlock",
    lang: "C#",
    family: "time",
    title: ".Result and .Wait() deadlock on a captured context",
    body: "Blocking on a task whose continuation needs the same single-threaded context deadlocks. It works in a console app and hangs in ASP.NET classic or WPF — so it passes every test the author ran.",
    fix: "await all the way up; ConfigureAwait(false) in library code",
  },
  {
    id: "cs-nrt",
    lang: "C#",
    family: "contract",
    title: "Nullable reference types are compile-time only",
    body: "A non-nullable string can hold null at runtime whenever the value crosses a boundary the compiler cannot see — deserialisation, reflection, or a library compiled without the feature.",
    fix: "Validate at the boundary; do not treat the annotation as a guarantee",
  },
  {
    id: "cs-firstordefault",
    lang: "C#",
    family: "boundary",
    title: "FirstOrDefault on a value type returns 0, not null",
    body: "For int, the 'not found' answer is 0 — a legitimate id, a legitimate count, a legitimate index. The absence is indistinguishable from a real value and no null check will catch it.",
    fix: "Use the bool-returning TryGetValue pattern, or work with nullable value types",
  },
  {
    id: "cs-tolower-culture",
    lang: "C#",
    family: "coercion",
    title: "ToLower() is culture-sensitive",
    body: 'Under a Turkish locale, "I".ToLower() is not "i", so case-insensitive comparisons of identifiers and file paths stop matching. It reproduces only on machines with that locale.',
    fix: "string.Equals(a, b, StringComparison.OrdinalIgnoreCase)",
  },
  {
    id: "cs-struct-copy",
    lang: "C#",
    family: "state",
    title: "Structs are copied on every assignment and argument pass",
    body: "Mutating a struct retrieved from a list or a dictionary mutates a copy and the change is silently discarded. The code reads exactly like the class version that works.",
    fix: "Prefer readonly structs, or use classes for anything mutable",
  },

  /* ----------------------------------- Bash --------------------------------- */
  {
    id: "sh-unquoted",
    lang: "Bash",
    family: "coercion",
    title: "Unquoted expansions word-split and glob",
    body: 'A path with a space becomes two arguments; a path with * is expanded against the filesystem. In an rm -rf that is the difference between deleting one directory and deleting several.',
    fix: 'Quote every expansion: "$VAR", "${arr[@]}"',
  },
  {
    id: "sh-unset-var",
    lang: "Bash",
    family: "boundary",
    title: "An unset variable expands to nothing",
    body: "`rm -rf $DIR/*` with DIR unset is `rm -rf /*`. There is no error and no warning; the shell simply substitutes emptiness and the command proceeds.",
    fix: 'set -u, and "${DIR:?DIR is required}"',
  },
  {
    id: "sh-no-set-e",
    lang: "Bash",
    family: "failure",
    title: "Without set -e a failing command does not stop the script",
    body: "The copy fails, the next line prints 'done', and cron reports success. The monitoring signal and the actual outcome are now decoupled and the failure is discovered at restore time.",
    fix: "set -euo pipefail at the top of every script",
  },
  {
    id: "sh-pipefail",
    lang: "Bash",
    family: "failure",
    title: "A pipeline's exit status is the last command's",
    body: "`curl ... | jq .` succeeds whenever jq succeeds, even if curl failed entirely. Without pipefail, every pipeline silently discards the status of everything but its final stage.",
    fix: "set -o pipefail, and check ${PIPESTATUS[@]} when you need per-stage status",
  },
  {
    id: "sh-dotglob",
    lang: "Bash",
    family: "boundary",
    title: "* does not match dotfiles",
    body: "`cp -r /src/* /dst/` silently omits .env, .ssh and .config, and the matching `rm /dst/*` leaves the stale ones in place. The backup looks complete because everything visible is there.",
    fix: "cp -a /src/. /dst/ — or rsync -a with a trailing slash",
  },
  {
    id: "sh-local-masks",
    lang: "Bash",
    family: "failure",
    title: "local masks the exit status of a command substitution",
    body: "`local out=$(cmd)` always succeeds, because the status reported is local's, not cmd's. Under set -e the failure is swallowed and the empty output is used.",
    fix: "Declare first, assign second: local out; out=$(cmd)",
  },
  {
    id: "sh-cd-unchecked",
    lang: "Bash",
    family: "failure",
    title: "An unchecked cd runs the rest of the script somewhere else",
    body: "If cd fails, execution continues in the previous directory and every relative path afterwards operates on the wrong tree — which, for a script that deletes things, is unrecoverable.",
    fix: 'cd "$dir" || exit 1',
  },
  {
    id: "sh-read-r",
    lang: "Bash",
    family: "coercion",
    title: "read without -r eats backslashes",
    body: "Backslash sequences in input lines are interpreted rather than preserved, so Windows paths and escaped characters are silently mangled while everything else works.",
    fix: "while IFS= read -r line; do",
  },

  /* ---------------------------------- C++ ----------------------------------- */
  {
    id: "cpp-accumulate-init",
    lang: "C++",
    family: "coercion",
    title: "std::accumulate takes its type from the init value",
    body: "The accumulator is deduced from the third argument, not from the iterators. Pass the literal 0 over a container of doubles and every addition truncates to int. No warning at any level, and a plausible number comes out.",
    code: "double avg = std::accumulate(v.begin(), v.end(), 0) / v.size();",
    fix: "std::accumulate(v.begin(), v.end(), 0.0)",
  },
  {
    id: "cpp-string-view-temp",
    lang: "C++",
    family: "state",
    title: "A string_view outliving the string it viewed",
    body: "string_view does not own anything. Constructing one from a temporary — a concatenation, a function returning by value, a to_string — leaves it pointing at freed memory at the end of the full expression. Debug builds usually still read the old bytes, so the bug ships.",
    code: 'std::string_view name = user.first() + " " + user.last();',
    fix: "Keep the std::string alive, or take ownership. The same applies to std::span and to const& members.",
  },
  {
    id: "cpp-size-underflow",
    lang: "C++",
    family: "boundary",
    title: "size() - 1 on an empty container",
    body: "size() returns an unsigned type, so 0 - 1 is SIZE_MAX rather than -1. A loop bounded by `i <= v.size() - 1` iterates about 18 quintillion times over an empty vector instead of zero times.",
    fix: "Compare as `i + 1 < v.size()`, or use ranges / iterators.",
  },
  {
    id: "cpp-map-subscript",
    lang: "C++",
    family: "state",
    title: "map::operator[] inserts on read",
    body: "Reading a missing key default-constructs a value and inserts it. A lookup in a logging or metrics path silently grows the map forever, and `if (m[k] == 0)` is a mutation. It is also not available on a const map, which is the only reason anyone notices.",
    fix: "m.at(k) to throw, m.find(k) to test, m.contains(k) in C++20.",
  },
  {
    id: "cpp-iterator-invalidation",
    lang: "C++",
    family: "state",
    title: "push_back invalidates every iterator, pointer and reference",
    body: "A single reallocation makes every previously taken reference dangle — including one captured before the loop as `auto& first = v[0]`. erase() invalidates everything from the erase point on. Both are undefined behaviour that a small test never triggers because the reserve happened to be large enough.",
    fix: "Re-index rather than holding references, or reserve() before the loop and say why in a comment.",
  },
  {
    id: "cpp-lambda-capture-ref",
    lang: "C++",
    family: "time",
    title: "A lambda capturing by reference, stored for later",
    body: "`[&]` on a lambda that outlives its enclosing scope — pushed onto a thread pool, stored as a callback, returned — captures dangling references. Capturing `this` implicitly via [&] or [=] has the same problem when the object is destroyed before the callback fires.",
    code: "pool.post([&] { send(payload); });   // payload is a local",
    fix: "Capture by value, or [self = shared_from_this()] when the callback can outlive the object.",
  },
  {
    id: "cpp-uninitialised-member",
    lang: "C++",
    family: "boundary",
    title: "An uninitialised scalar member",
    body: "`int count;` in a class body has an indeterminate value until assigned. Reading it is undefined behaviour, and in practice it is often zero in a debug build and garbage under optimisation — the worst possible split, because the test suite passes.",
    fix: "int count = 0; — default member initialisers for every scalar, every time.",
  },
  {
    id: "cpp-use-after-move",
    lang: "C++",
    family: "state",
    title: "Using an object after std::move",
    body: "A moved-from standard object is valid but unspecified. `v.size()` after moving v is legal and returns something nobody should rely on — usually 0, sometimes not. std::move on a const object or a const&& silently does not move at all, so the copy you were avoiding still happens.",
    fix: "Treat a moved-from variable as dead. Clang-tidy's bugprone-use-after-move finds these.",
  },

  /* --------------------------------- Kotlin --------------------------------- */
  {
    id: "kt-platform-types",
    lang: "Kotlin",
    family: "failure",
    title: "Platform types from Java are not checked",
    body: "An unannotated Java method returns `String!`, which Kotlin lets you assign to a non-null `String` with no complaint. The null check happens at the assignment as an intrinsic, so the NullPointerException blames a line that does not mention null and the value's real origin is a frame or two up.",
    fix: "Type the boundary as nullable (`String?`) and handle it there, once.",
  },
  {
    id: "kt-elvis-not-validation",
    lang: "Kotlin",
    family: "failure",
    title: "?: only covers null, not a thrown conversion",
    body: "`s?.toInt() ?: 0` looks like it tolerates bad input. It tolerates a *missing* value; a present but unparseable one throws NumberFormatException, which the elvis operator never sees. The shape of the line advertises a safety it does not have.",
    fix: "s?.toIntOrNull() ?: 0",
  },
  {
    id: "kt-data-class-copy",
    lang: "Kotlin",
    family: "state",
    title: "data class copy() is shallow, and equals ignores body properties",
    body: "copy() copies references, so a nested MutableList is shared with the original. Separately, the generated equals, hashCode and toString consider only the *primary constructor* parameters — a property declared in the class body is silently excluded, so two unequal objects compare equal.",
    fix: "Copy nested collections explicitly, and keep every property that defines identity in the primary constructor.",
  },
  {
    id: "kt-int-overflow",
    lang: "Kotlin",
    family: "coercion",
    title: "Int arithmetic wraps silently",
    body: "There is no overflow check: `Int.MAX_VALUE + 1` is Int.MIN_VALUE. Milliseconds, byte counts and cents all pass 2.1 billion in real systems, and the result is a large negative number that propagates into a duration or a size.",
    fix: "Long for anything counting time, bytes or money — or Math.addExact to fail loudly.",
  },
  {
    id: "kt-extension-static",
    lang: "Kotlin",
    family: "contract",
    title: "Extension functions dispatch statically",
    body: "An extension is resolved from the *declared* type of the receiver, not its runtime class. An extension on Animal is called even when the value is a Dog and an extension on Dog exists. It reads exactly like an overridable method and is not one.",
    fix: "Use a real member function when the behaviour must vary by subtype.",
  },
  {
    id: "kt-globalscope-launch",
    lang: "Kotlin",
    family: "failure",
    title: "GlobalScope.launch drops exceptions and ignores cancellation",
    body: "A coroutine launched in GlobalScope is tied to nothing: the caller cannot await it, an exception goes to the (usually absent) handler and vanishes, and cancelling the request that started it has no effect. It is the Kotlin spelling of async void.",
    fix: "Launch in a scope with a lifecycle, and use async/await when the result matters.",
  },
  {
    id: "kt-nan-equals",
    lang: "Kotlin",
    family: "coercion",
    title: "== and equals disagree on NaN and -0.0",
    body: "For statically-known Double, `==` is IEEE 754: NaN != NaN, and 0.0 == -0.0. Once the values are boxed — inside a List, a Map key, a generic — Kotlin uses equals(), where NaN *is* equal to NaN and 0.0 is *not* equal to -0.0. So `listOf(Double.NaN).contains(Double.NaN)` is true while `x == y` is false for the same pair.",
    fix: "Never key a collection on a floating-point value. Compare with a tolerance you chose.",
  },
  {
    id: "kt-no-checked-exceptions",
    lang: "Kotlin",
    family: "failure",
    title: "Java's checked exceptions are invisible",
    body: "Kotlin has no checked exceptions, so a call into a Java library that declares `throws IOException` carries no signal at the call site and no compiler pressure to handle it. Generated Kotlin wrapping a Java SDK routinely has no error path at all for calls that are documented to fail.",
    fix: "Read the Java signature. Wrap the boundary in runCatching or a Result type deliberately.",
  },
  {
    id: "kt-readonly-not-immutable",
    lang: "Kotlin",
    family: "state",
    title: "List is read-only, not immutable",
    body: "`val items: List<T>` only means *you* cannot add to it. If it was produced by `toList()` on a MutableList it is a copy, but if it was cast or returned directly from a mutable backing field, the owner can still change it under you. A `val` of a collection type says nothing about the collection's contents.",
    fix: "Return items.toList() from the getter, or use kotlinx.collections.immutable.",
  },

  /* ---------------------------------- Ruby ---------------------------------- */
  {
    id: "rb-to-i",
    lang: "Ruby",
    family: "coercion",
    title: "to_i never raises",
    body: 'nil.to_i is 0, "abc".to_i is 0, "12abc".to_i is 12, "1e9".to_i is 1 and " 7 ".to_i is 7. Every malformed input becomes a plausible number, so the parameter is never validated and the failure surfaces as a wrong total.',
    fix: "Integer(value, exception: false), then reject nil explicitly.",
  },
  {
    id: "rb-zero-truthy",
    lang: "Ruby",
    family: "coercion",
    title: "0 and \"\" are truthy",
    body: 'Only nil and false are falsy. `if count` is true when count is 0, and `if name` is true when name is "". Generated Ruby often carries a truthiness idiom straight over from Python or JavaScript, where both of those are false, and the branch then runs in exactly the case it was written to skip.',
    fix: "Be explicit: `if count.positive?`, `if name.present?`, `unless value.nil?`.",
  },
  {
    id: "rb-or-equals-false",
    lang: "Ruby",
    family: "state",
    title: "||= re-runs whenever the value is false or nil",
    body: "`@enabled ||= expensive_check` memoises everything except false — which is the answer the check most often gives. So the expensive call happens on every access for exactly the objects where it returns false, and a method that looks memoised is not.",
    fix: "defined?(@enabled) ? @enabled : (@enabled = expensive_check)",
  },
  {
    id: "rb-and-or-precedence",
    lang: "Ruby",
    family: "contract",
    title: "and/or bind looser than assignment",
    body: "`x = a or b` parses as `(x = a) or b`, so x never receives b and the second operand is evaluated for nothing. The line reads as an ordinary default. Ruby only warns under -w, which nobody enables in a generated snippet.",
    fix: "Use || and && in expressions; keep and/or for control flow (`save or raise`).",
  },
  {
    id: "rb-hash-default-shared",
    lang: "Ruby",
    family: "state",
    title: "Hash.new([]) shares one default object",
    body: "The default is a single array handed to every missing key, and reading a missing key does not store anything. So `h[:a] << 1; h[:b] << 2` mutates the same array, h stays empty, and h[:a] returns [1, 2].",
    code: "h = Hash.new([])\nh[:a] << 1\nh.keys  # => []",
    fix: "Hash.new { |hash, k| hash[k] = [] }",
  },
  {
    id: "rb-integer-division",
    lang: "Ruby",
    family: "coercion",
    title: "Integer / Integer truncates",
    body: "1999 * 10 / 100 is 199, not 200. For cents that is a rounding rule nobody chose, applied consistently in one direction, and it will disagree with the finance spec at every amount that is not a clean multiple.",
    fix: "fdiv for a float, or (a * b).divmod(100) / Rational / BigDecimal when the rule matters.",
  },
  {
    id: "rb-dup-shallow",
    lang: "Ruby",
    family: "state",
    title: "dup and clone are shallow",
    body: "The new object's references point at the same nested hashes and arrays, so mutating `copy[:items]` mutates the original. `freeze` is shallow for the same reason: a frozen hash's values are still mutable.",
    fix: "Marshal.load(Marshal.dump(obj)) for a deep copy, or build the nested structure explicitly.",
  },
  {
    id: "rb-bare-rescue",
    lang: "Ruby",
    family: "failure",
    title: "rescue with no class also swallows your typos",
    body: "`rescue => e` catches StandardError, which includes NoMethodError, NameError and ArgumentError. So a misspelled method inside the begin block is caught and reported as whatever the rescue says the failure means — 'payment gateway unavailable' for a typo. A bare `rescue nil` at the end of a line is the same thing with no log at all.",
    fix: "Rescue the specific classes the block can actually raise, and re-raise anything else.",
  },

  /* ----------------------------------- PHP ---------------------------------- */
  {
    id: "php-loose-equals-hash",
    lang: "PHP",
    family: "coercion",
    title: "== still compares two numeric strings numerically",
    body: 'PHP 8 stopped juggling non-numeric strings against numbers, but two numeric *strings* are still compared as numbers. md5 output of the form "0e123..." is a numeric string, so any two such hashes compare equal under ==. Attackers precompute them, and both == and === leak timing.',
    fix: "hash_equals($known, $given) — and hash_hmac('sha256', ...) rather than md5.",
  },
  {
    id: "php-strpos-zero",
    lang: "PHP",
    family: "coercion",
    title: "strpos returns 0 for a match at the start and false for none",
    body: "`if (strpos($s, $needle))` is false for a match at position 0. `if (strpos($s, $needle) == 0)` is true when there is *no* match, because false == 0. Both readings of the loose comparison are wrong, in opposite directions, and each passes a test written for the other case.",
    fix: "str_starts_with / str_contains in PHP 8, or === 0 and !== false.",
  },
  {
    id: "php-array-merge-renumber",
    lang: "PHP",
    family: "state",
    title: "array_merge renumbers integer keys",
    body: "Merging two arrays with integer keys appends and reindexes rather than overwriting, so a config array keyed 0,1,2 silently doubles in size instead of having its entries replaced. The + operator does the opposite and keeps the left-hand value, which is equally surprising in the other direction.",
    fix: "array_replace for integer keys; array_merge only for string-keyed maps and true lists.",
  },
  {
    id: "php-array-filter-keys",
    lang: "PHP",
    family: "contract",
    title: "array_filter preserves keys, so json_encode emits an object",
    body: 'Filtering [0=>a, 1=>b, 2=>c] down to the middle element leaves the key 1 in place. json_encode then produces {"1":"b"} rather than ["b"], and the client — which is typed to expect an array — breaks on a response that is valid JSON. It only shows up when the *first* element is the one filtered out.',
    fix: "array_values(array_filter(...)) whenever the result is serialised as a list.",
  },
  {
    id: "php-foreach-reference",
    lang: "PHP",
    family: "state",
    title: "foreach by reference leaves the reference behind",
    body: "After `foreach ($a as &$v)` the variable $v is still a reference to the last element. A second, ordinary `foreach ($a as $v)` then writes each value through that reference, and the last element of the array ends up holding the second-to-last value. The corruption is in the array, one element only, with no error.",
    fix: "unset($v); immediately after any by-reference foreach.",
  },
  {
    id: "php-empty-zero",
    lang: "PHP",
    family: "coercion",
    title: "empty() is true for 0, \"0\", \"\" and []",
    body: 'A quantity of 0, a page "0" and a literal zero-valued setting are all "empty", so `if (empty($qty))` rejects a legitimate value. isset() is the opposite trap: it is false for a key that exists with a null value.',
    fix: "Compare against what you actually mean: $qty === null, or array_key_exists.",
  },
  {
    id: "php-sort-in-place",
    lang: "PHP",
    family: "state",
    title: "sort() mutates and returns a bool",
    body: "`$sorted = sort($items);` assigns true, not a sorted array, and reorders the caller's $items in place. sort() also discards keys entirely, so sorting an associative array destroys it.",
    fix: "sort($items); then use $items — or usort with an explicit comparator; asort/ksort to keep keys.",
  },
  {
    id: "php-in-array-loose",
    lang: "PHP",
    family: "coercion",
    title: "in_array without the strict flag",
    body: 'The default comparison is ==, so in_array(null, [""]) is true and in_array(0, [false]) is true. Permission and status checks written this way accept a value the list does not contain, and the same applies to array_search and array_keys.',
    fix: "in_array($needle, $haystack, true) — always pass the third argument.",
  },
];

export const GOTCHA_LANGS: Lang[] = [
  "Python",
  "JavaScript",
  "TypeScript",
  "SQL",
  "Rust",
  "Go",
  "Java",
  "C#",
  "C++",
  "Kotlin",
  "Ruby",
  "PHP",
  "Bash",
];
