import type { Drill } from "../../types";

import s31 from "../samples/31-flags.rb?raw";
import s32 from "../samples/32-pricing.php?raw";
import s33 from "../samples/33-invoicedates.kt?raw";
import s34 from "../samples/34-reindex.sh?raw";
import s35 from "../samples/35-pricecache.rs?raw";
import s36 from "../samples/36-sessions.cpp?raw";
import s37 from "../samples/37-charge.diff?raw";
import s38 from "../samples/38-rates.diff?raw";
import s39 from "../samples/39-ratetable.go?raw";
import s40 from "../samples/40-rollup.java?raw";
import s41 from "../samples/41-claim.diff?raw";
import s42 from "../samples/42-limiter.js?raw";
import s43 from "../samples/43-digest.py?raw";
import s44 from "../samples/44-autosave.diff?raw";
import s45 from "../samples/45-tokensource.ts?raw";

const t = (s: string) => s.replace(/\s+$/, "");

/**
 * Batch B — ids 31 to 45.
 *
 * Written to fill what the first thirty left thin: shared state and time &
 * concurrency defects, a wider warm-up on-ramp, more diffs, and a second drill
 * for each of the six languages that only had one. Do not append to this batch
 * from another issue; claim the next range and add a module.
 */
export const DRILLS_BATCH_B: Drill[] = [
  {
    id: 31,
    slug: "feature-flags",
    lang: "Ruby",
    level: "Warm-up",
    title: "Per-request feature flags",
    shape: "function",
    code: t(s31),
    brief:
      "Flags come from a file written by the deploy; a request may override one for a single user.",
    hintRegion:
      "The last line of `enabled?` decides three of these. The other one is in `load_flags`.",
    hintFamily: "Shared state, Silent coercion, Failure surface.",
    defects: [
      {
        family: "state",
        title: "An override to `false` is discarded",
        signal: "silent",
        severity: "blocker",
        body:
          "`@overrides[name] || @flags[name] || DEFAULTS[name]` cannot express 'overridden to off', because `false` is falsy in Ruby and falls through to the next term. `override!(\"new_search\", false)` followed by `enabled?(\"new_search\")` evaluates `false || nil || true` and returns **true**. The per-user kill switch — the reason overrides exist — works in exactly one direction, and the direction it fails in is the one you reach for during an incident.",
        fix:
          "Test for presence, not truthiness: `return @overrides[name] if @overrides.key?(name)`, then the same for `@flags`.",
      },
      {
        family: "state",
        title: "`tags << \"internal\"` mutates the caller's array",
        signal: "silent",
        severity: "major",
        body:
          "`<<` appends in place to the array the caller passed. A handler that builds one `tags` array per request and then asks about ten flags ends up with ten copies of `\"internal\"` in it, and whatever that array feeds — a log line, a metrics label, a cache key — changes shape depending on how many flags were consulted. The method reads like a pure query and its name says it is one.",
        fix: "`tags = tags + [\"internal\"] if ...`, or take the tags as a frozen argument.",
      },
      {
        family: "coercion",
        title: "A JSON `\"false\"` turns the flag on",
        signal: "silent",
        severity: "major",
        body:
          "Only `nil` and `false` are falsy in Ruby, so the string `\"false\"` is truthy. A flag file that writes `{\"beta_checkout\": \"false\"}` — which is what happens the moment the file is generated by a shell template, an env var dump or a YAML-to-JSON step — enables the flag. The file says off, the code says on, and nothing in either is wrong on its face.",
        fix:
          "Coerce at the boundary: parse the file into real booleans and reject a value that is neither `true` nor `false`.",
      },
      {
        family: "failure",
        title: "A malformed flag file is swallowed",
        signal: "silent",
        severity: "major",
        body:
          "`rescue Errno::ENOENT, JSON::ParserError` returns `{}` with no log line. A deploy that writes a truncated file then serves every flag from `DEFAULTS`: every experiment silently reverts to its shipped value, for every request, and the only symptom is a metrics step change with no deploy marker that explains it. The missing-file and corrupt-file cases also deserve different answers — one is a first boot, the other is a broken deploy.",
        fix:
          "Log and re-raise on a parse error; treat a missing file as fatal at boot rather than per call.",
      },
    ],
  },
  {
    id: 32,
    slug: "cart-pricing-static",
    lang: "PHP",
    level: "Warm-up",
    title: "Cart total with tax and a coupon",
    shape: "function",
    code: t(s32),
    brief: "Checkout calls this once per cart. Money is in whole cents throughout.",
    hintRegion: "The word `static` on line 22 changes what the rest of the method means.",
    hintFamily: "Shared state, Boundaries, Silent coercion.",
    defects: [
      {
        family: "state",
        title: "`static` caches the table against the first state seen",
        signal: "silent",
        severity: "blocker",
        body:
          "A `static` local in PHP is initialised once and then persists for the life of the process, not the call. The `$rates[$state] ?? 0.0` line therefore runs for the *first* cart only, so a later cart shipping to a state absent from `TAX` — say `'TX'` — reads an undefined key: PHP 8 emits a warning and evaluates it to `null`, `1 + null` is 1, and the cart ships untaxed. Under FPM, where the process is usually fresh, this never reproduces; under a persistent worker (Swoole, RoadRunner, a queue consumer) it depends on the order carts arrive in.",
        fix:
          "Drop the `static` — the const is already built once — and look the rate up with an explicit `array_key_exists` check that throws on an unknown state.",
      },
      {
        family: "boundary",
        title: "The coupon percentage is never clamped",
        signal: "silent",
        severity: "blocker",
        body:
          "`$coupon` is whatever the caller passes. 150 makes `$subtotal` negative, tax on a negative subtotal is negative, and the method returns a negative total — an order that pays the customer. Nothing in the signature or the docblock says the value must be 0–100, and a `?int` type tells you nothing about range.",
        fix: "Reject anything outside 0..100 before applying it, and assert the total is >= 0 on the way out.",
      },
      {
        family: "coercion",
        title: "`(int)` truncates a float total",
        signal: "silent",
        severity: "major",
        body:
          "`$subtotal * $coupon / 100` turns an int subtotal into a float, and `(int)` truncates toward zero rather than rounding. A cart of 1999 cents with a 10% coupon is 1799.1, taxed to 1956.61, truncated to 1956 — a cent below the correct 1957. The receipt that itemises the lines rounds each one and disagrees with this number, and the difference is a cent, which is exactly small enough for nobody to file a bug and exactly large enough for the payment processor's reconciliation to fail.",
        fix:
          "Stay in integer cents: `intdiv($subtotal * $coupon, 100)`, and `(int) round(...)` for the tax, with the rounding rule stated.",
      },
    ],
  },
  {
    id: 33,
    slug: "invoice-dates",
    lang: "Kotlin",
    level: "Warm-up",
    title: "Invoice date formatting",
    shape: "function",
    code: t(s33),
    brief: "Renders and compares the dates on a customer statement. Called from request threads.",
    hintRegion:
      "Two defects are in the two `private val`s, before any method runs. The other two are in `isCurrent`.",
    hintFamily: "Shared state, Time & concurrency.",
    defects: [
      {
        family: "state",
        title: "A shared SimpleDateFormat is not thread safe",
        signal: "silent",
        severity: "blocker",
        body:
          "`SimpleDateFormat` keeps mutable parse state in an internal `Calendar`, and this one is a field of a Kotlin `object` — a process-wide singleton. Two request threads formatting at the same moment interleave writes to that calendar. The result is not an exception: it is a valid-looking date with digits from the other thread's invoice. A statement shows a date that belongs to a different customer's invoice, and it happens on a small fraction of concurrent renders, so it reads as a data problem rather than a formatting one.",
        fix:
          "Use `java.time.format.DateTimeFormatter`, which is immutable and thread safe, or construct a `SimpleDateFormat` per call, or hold one in a `ThreadLocal`.",
      },
      {
        family: "time",
        title: "The formatter has no time zone",
        signal: "silent",
        severity: "major",
        body:
          "`SimpleDateFormat` with no explicit zone formats in the JVM default zone, so the same `Date` — the same instant — renders as a different calendar day depending on which host does the rendering. An invoice issued at 23:30 UTC prints as the previous day on a host set to UTC-5, and `period()` then files it in the previous billing month. The statement and the ledger disagree, and which one is wrong depends on which machine rendered it.",
        fix:
          "Pin the zone explicitly to the one the invoice is denominated in, and make it a parameter rather than a default.",
      },
      {
        family: "state",
        title: "The cache is keyed on the millisecond and never bounded",
        signal: "silent",
        severity: "major",
        body:
          "`cache.getOrPut(at.time)` keys on the exact epoch millisecond, so two renders of the same invoice only share an entry if their `Date` objects are millisecond-identical — which they are when the same object is passed twice, and are not when the date is re-read from the row. The map is an unbounded `mutableMapOf` (a `HashMap`) written from many threads with no synchronisation, so it grows for the life of the process and a concurrent resize can lose entries or spin. Note the trap in the obvious fix: keying on the *day* makes the formatter almost never run, which hides the thread-safety defect above until production traffic finds it.",
        fix:
          "Drop the cache — `DateTimeFormatter` is cheap — or use a bounded, concurrent cache keyed on the value you actually want to reuse.",
      },
      {
        family: "time",
        title: "The payment window is measured in fixed 24-hour days",
        signal: "silent",
        severity: "minor",
        body:
          "`(now.time - issued.time) / (1000 * 60 * 60 * 24)` truncates, so 30 days and 23 hours reports 30 and the invoice is still 'current' — the window is really 31 days. It also counts fixed 86,400,000 ms units, which is not what a calendar day is: a 30-day window spanning a spring-forward transition is an hour short of 30 calendar days, so on one day a year the window closes early. The terms say 30 days; the code implements neither 30 days nor 30×24 hours.",
        fix:
          "`ChronoUnit.DAYS.between` on `LocalDate`s in the invoice's zone, and decide out loud whether the bound is inclusive.",
      },
    ],
  },
  {
    id: 34,
    slug: "reindex-lock",
    lang: "Bash",
    level: "Warm-up",
    title: "Single-instance reindex",
    shape: "function",
    code: t(s34),
    brief: "Run from cron every hour. A run that finds the lock held is meant to do nothing.",
    hintRegion: "Line 11 is in the wrong place. Start by asking what runs when the lock is held.",
    hintFamily: "Shared state, Time & concurrency, Failure surface.",
    defects: [
      {
        family: "state",
        title: "The EXIT trap deletes a lock this run does not own",
        signal: "silent",
        severity: "blocker",
        body:
          "`trap 'rm -f $LOCK' EXIT` is installed *before* the lock is tested, so the 'already running' branch removes the running instance's lock file on its way out. The second invocation therefore unlocks the first, and the third starts a concurrent reindex against the same directory while the first is still writing `index.new`. The script's log says 'already running' and stops, which is exactly what it is supposed to say — the damage is done by the line that runs after the `exit`.",
        fix:
          "Install the trap only after the lock is acquired, and have it remove the file only if the pid inside is `$$`.",
      },
      {
        family: "time",
        title: "Check-then-act on the lock file",
        signal: "silent",
        severity: "blocker",
        body:
          "`[ -f $LOCK ]` and `echo $$ > $LOCK` are two operations with a gap between them. Two cron runs that fire in the same second — which happens after a host resumes from suspend, or when the previous run overran by an hour — both see no lock, both write their pid, and both reindex. The `mv` at the end then races: whichever finishes second wins, and the surviving index may be a mix of two runs' output. Fixing this without fixing the trap above leaves the concurrency intact.",
        fix:
          "Use an atomic primitive: `mkdir \"$LOCK\"` (fails if it exists) or, better, wrap the body in `flock -n`.",
      },
      {
        family: "failure",
        title: "Unquoted, unvalidated `$1`",
        signal: "mixed",
        severity: "blocker",
        body:
          "With no argument, `DATA` is empty and unquoted, so `find $DATA -name '*.idx' -mtime +7 -delete` becomes `find -name '*.idx' -mtime +7 -delete` and deletes index files under the *current* directory — whatever cron's working directory happens to be. `$DATA/index.new` becomes `/index.new`. A path containing a space splits into two arguments and deletes from a directory nobody named. `set -e` does not help, because none of this fails.",
        fix:
          "`set -euo pipefail`, quote every expansion, and `[[ -d $DATA ]] || { echo 'usage: reindex.sh DIR' >&2; exit 2; }`.",
      },
      {
        family: "failure",
        title: "The contended path exits 0",
        signal: "silent",
        severity: "major",
        body:
          "`exit 0` tells cron, and any wrapper watching the status, that the reindex succeeded. If one run wedges and holds its lock, every subsequent hourly run reports success while the index goes stale indefinitely. The one condition that most needs an alert is the one that is reported as healthy. `$(cat $LOCK)` in the message is also unquoted and unchecked, so a truncated lock file prints an empty pid.",
        fix:
          "Exit non-zero (or emit a metric) when the lock is held, and alert on a lock older than one run interval.",
      },
    ],
  },
  {
    id: 35,
    slug: "rust-price-cache",
    lang: "Rust",
    level: "Standard",
    title: "Rendered price table cache",
    shape: "function",
    code: t(s35),
    brief:
      "Rendering a price table takes about two seconds. Request threads call `get`; a sweeper thread calls `sweep`.",
    hintRegion:
      "Both methods release one lock and take another. Ask what can happen in the gap, in each of them.",
    hintFamily: "Shared state, Time & concurrency, Failure surface.",
    defects: [
      {
        family: "time",
        title: "No single flight: every concurrent miss renders",
        signal: "silent",
        severity: "major",
        body:
          "`get` drops the read guard before taking the write guard. Fifty threads that miss at the same instant all call `render`, all take two seconds, and all insert — so a cold start or a TTL expiry on a hot key costs fifty renders instead of one, and the fiftieth writer's timestamp is the one that survives. Worse for correctness: a caller can be handed a value that is immediately replaced by a *different* render, so two requests in the same millisecond can see two different price tables.",
        fix:
          "Hold a per-key single-flight: insert a shared `Arc<OnceLock>` (or a `tokio::sync::Mutex` per key) under the write lock, then render outside it and let the other callers await the same cell.",
      },
      {
        family: "state",
        title: "`sweep` removes entries it has not re-checked",
        signal: "silent",
        severity: "major",
        body:
          "`sweep` collects stale keys under the read lock, drops it, then removes them under the write lock. A key that was stale during the collect pass may have been re-rendered in the gap — which for a hot key is the common case — and `remove` throws the fresh entry away. The next `get` re-renders, so the symptom is a two-second latency spike on a key that was just populated, at an interval set by the sweeper rather than by the TTL. This defect is invisible while the bug above is present: the render herd keeps every hot key warm, so a needless eviction costs nothing you can measure. Fixing single-flight is what makes it show up.",
        fix:
          "Do the whole sweep under the write lock, or re-check `at.elapsed() >= ttl` inside the write section before removing.",
      },
      {
        family: "failure",
        title: "`.unwrap()` on the lock makes one panic permanent",
        signal: "mixed",
        severity: "major",
        body:
          "`render` is caller-supplied and runs outside the lock, but any panic *inside* a lock section — an allocation failure, an arithmetic overflow in debug, a panic in a `Drop` — poisons the `RwLock`. Every subsequent `get`, `sweep` and `len` then unwraps an `Err` and panics in turn, so a single transient fault turns the cache into a permanent process-wide outage, and every stack trace points at this file rather than at whatever panicked first.",
        fix:
          "Handle poisoning explicitly (`unwrap_or_else(|e| e.into_inner())` when the data is still sound), or use a non-poisoning lock such as `parking_lot::RwLock`.",
      },
      {
        family: "failure",
        title: "A failing render has nowhere to go",
        signal: "silent",
        severity: "major",
        body:
          "`render: impl Fn(&str) -> String` cannot report failure. A closure that cannot reach the pricing service must either panic — see above — or return a string that says so, and the cache will then store that string for the full TTL and serve it to every caller as a price table. The signature makes the wrong thing the easy thing.",
        fix:
          "`render: impl Fn(&str) -> Result<String, E>`, and do not insert on `Err`; return the previous value if there is one.",
      },
      {
        family: "boundary",
        title: "Unbounded map keyed on a caller-supplied string",
        signal: "silent",
        severity: "major",
        body:
          "`region` is a `&str` from the caller with no validation, and nothing caps the map's size. If `region` is ever reachable from a query parameter, an unauthenticated client can insert a distinct entry per request, each holding a rendered table, and `sweep` only reclaims them a TTL later — so the ceiling is (request rate x TTL) entries, not the dozen regions that actually exist. There is no `len` limit and no eviction policy other than age.",
        fix: "Validate `region` against the known set, and cap the map with an LRU eviction.",
      },
    ],
  },
  {
    id: 36,
    slug: "session-registry",
    lang: "C++",
    level: "Standard",
    title: "Connected session registry",
    shape: "function",
    code: t(s36),
    brief:
      "The accept loop calls `Add`, worker threads call `Find` to route a message, and the socket teardown calls `Remove`.",
    hintRegion:
      "`Add` returns something the caller keeps. `Remove` changes something `Find` depends on. Both matter.",
    hintFamily: "Shared state, Boundaries, Time & concurrency.",
    defects: [
      {
        family: "state",
        title: "`Add` returns a reference into a vector that reallocates",
        signal: "silent",
        severity: "blocker",
        body:
          "`sessions_.push_back` invalidates every reference, pointer and iterator into the vector whenever it grows past capacity. `Add` hands the caller a reference to `sessions_.back()`, and the doc comment invites them to keep it and update `pending` in place. The next connection can reallocate, and that write then lands in freed memory: usually nothing visible, sometimes a corrupted heap, always at a moment unrelated to the code that caused it. It compiles, it passes a test that adds one session, and it survives until traffic exceeds the initial capacity.",
        fix:
          "Store `std::unique_ptr<Session>` (or use a `std::deque`/node-based container) so element addresses are stable, and return a handle or an id rather than a reference.",
      },
      {
        family: "state",
        title: "`Remove` shifts the vector and leaves the index stale",
        signal: "silent",
        severity: "blocker",
        body:
          "`sessions_.erase(begin() + it->second)` moves every later element down one slot, but only the removed key is erased from `index_`. Every session added after the removed one now maps to the slot of its neighbour, so `Find` returns the **wrong session** — and a message is delivered to the wrong user's socket, with the right-looking id on it. The registry keeps working, `Count()` is correct, and the defect scales with how many disconnects have happened.",
        fix:
          "Swap-and-pop and repair the moved element's index entry, or key the container on the id and keep insertion order in a separate list of ids.",
      },
      {
        family: "time",
        title: "`Find`, `All` and `Count` take no lock",
        signal: "silent",
        severity: "blocker",
        body:
          "`Add` and `Remove` lock `mu_`; `Find`, `All` and `Count` do not. A `Find` running during a `Remove`'s `erase` reads elements that are being shifted under it, and a `Find` during an `Add`'s reallocation reads through a dangling `data()`. `All` hands the admin page a reference to a vector that other threads are resizing. This is the defect the index-shift bug above hides: while `Find` is already returning wrong sessions for a structural reason, nobody attributes anything to the missing lock. Fixing the index is what leaves the race as the only explanation left.",
        fix:
          "Lock in every accessor. `mu_` must be `mutable` for the `const` ones, and `All` must return a copy — handing out a reference to shared state cannot be made safe by a lock inside the accessor.",
      },
      {
        family: "contract",
        title: "A duplicate id orphans a row forever",
        signal: "silent",
        severity: "major",
        body:
          "`Add` never checks whether `id` is already present. A reconnect that reuses its session id pushes a second `Session` and overwrites the index entry, so the first row is unreachable: `Remove` deletes the newer one and the older one stays for the life of the process. `Count()` and the admin page keep climbing while the real connection count does not, and the leak is slow enough to read as normal growth.",
        fix:
          "Return an error or the existing session on a duplicate id, and state in the comment whether reusing an id is legal.",
      },
    ],
  },
  {
    id: 37,
    slug: "charge-retry",
    lang: "Python",
    level: "Standard",
    title: "Retry a flaky payment gateway",
    shape: "diff",
    code: t(s37),
    brief:
      "The gateway times out a few times a day. This change adds retries so those requests stop surfacing as failed payments.",
    hintRegion:
      "The loop is correct Python. Ask what the gateway has already done by the time it raises, and which errors reach this handler.",
    hintFamily: "Time & concurrency, Failure surface, Boundaries.",
    defects: [
      {
        family: "time",
        title: "The retry is not idempotent — the customer is charged twice",
        signal: "silent",
        severity: "blocker",
        body:
          "`gateway.charge` carries no idempotency key, so the gateway cannot tell attempt two from a second purchase. The failure this retry exists for is a *timeout*, and a timeout is precisely the case where the charge may already have succeeded — we lost the response, not the request. Three attempts can move the money three times, and because only the final `result.reference` is written to `Charge`, the duplicates do not exist in our own data at all. The first evidence is a chargeback.",
        fix:
          "Generate an idempotency key per logical charge, pass it on every attempt, and persist it before the first call so a retry after a process restart reuses it.",
      },
      {
        family: "failure",
        title: "A decline is retried like a timeout",
        signal: "mixed",
        severity: "major",
        body:
          "`except gateway.GatewayError` is the only handler, and a hard decline almost certainly raises the same class. So an insufficient-funds decline is submitted three times: the card network reads repeated declines as a fraud signal and may block the card, the customer gets three declined-payment notifications, and the call takes three extra seconds to return the same answer it had immediately. This is also what hides the defect above — the easy failure to reproduce in staging is a decline, which never charges, so the duplicate-charge path is never exercised until production times out.",
        fix:
          "Retry only on the errors that are actually transient (timeout, 5xx, connection reset) and raise terminal errors on the first attempt. That distinction has to exist in the gateway client, not here.",
      },
      {
        family: "time",
        title: "Blocking sleep with no jitter, in a request path",
        signal: "silent",
        severity: "major",
        body:
          "`time.sleep(2 ** attempt)` blocks the worker for 1 then 2 seconds, so the worst case adds three seconds to a request that is going to fail anyway — long enough for the client to time out and, if the client retries, to start the whole thing again from the top. There is no jitter, so a gateway blip backs every in-flight request off by the same amount and they all return together: the recovery attempt is a synchronised thundering herd aimed at a dependency that is already unwell. No overall deadline bounds the total either.",
        fix:
          "Randomised exponential backoff with a cap, an overall deadline passed in by the caller, and the retry moved to a queue rather than a request thread.",
      },
      {
        family: "boundary",
        title: "`attempts=0` raises `TypeError`, not the gateway error",
        signal: "loud",
        severity: "minor",
        body:
          "`range(0)` is empty, so the loop body never runs, the `else` clause fires, and `raise last_error` raises `None` — `TypeError: exceptions must derive from BaseException`. Any caller that threads a configured retry count through and lands on 0 to mean 'do not retry' gets a type error from inside the billing module instead of the payment error it was handling.",
        fix: "Validate `attempts >= 1`, and guard the `raise` on `last_error is not None`.",
      },
      {
        family: "contract",
        title: "No caller was changed, and the charge is still not recorded atomically",
        signal: "silent",
        severity: "blocker",
        body:
          "The two defects that are not in the changed lines. First, `attempts: int = 3` means every existing call site silently acquires retry behaviour with no review of whether it is safe there — a bulk payout job now triples its worst-case runtime and its duplicate-charge exposure. Second, the `Charge` row is still created *after* the gateway call and outside any transaction with it, so a process death in that window moves money with no local record; the retry loop widens that window from one call to three plus three seconds of sleep. Neither an idempotency-key column nor a migration appears in this change.",
        fix:
          "Make the new behaviour opt-in at each call site, and write an intent row with the idempotency key *before* the first gateway call so a crash is recoverable.",
      },
    ],
  },
  {
    id: 38,
    slug: "rates-cache-diff",
    lang: "TypeScript",
    level: "Standard",
    title: "Cache the FX rate table",
    shape: "diff",
    code: t(s38),
    brief:
      "Every order converts currency, and the gateway bills per call. This change caches the table for a minute.",
    hintRegion:
      "There is a non-null assertion in the new code. There is also an argument the cache does not account for.",
    hintFamily: "Shared state, Time & concurrency, Failure surface, Contract.",
    defects: [
      {
        family: "state",
        title: "The cache ignores `base`",
        signal: "silent",
        severity: "blocker",
        body:
          "`cached` is a single module-level slot, but `getRates` takes a base currency. The first caller's table is served to every other base for the next minute, so `convert(amount, \"GBP\", rates)` multiplies by a GBP quote struck against EUR when the caller asked for USD. The returned object even carries the honest `base` field that would reveal it, and `convert` never looks at it. Every number is plausible and every number is wrong by an exchange rate.",
        fix: "Key the cache on `base` — a `Map<string, Rates>` — and have `convert` assert `rates.base` matches what it was asked for.",
      },
      {
        family: "state",
        title: "`return cached!` returns null on a cold start",
        signal: "loud",
        severity: "blocker",
        body:
          "On the first requests after a deploy, `cached` is `null` and the first caller has set `refreshing = true`. Every concurrent caller takes the `if (refreshing)` branch and returns `cached!` — `null`, laundered through a non-null assertion that exists only to make the compiler agree. `convert` then throws on `rates.quotes`. The cache fails hardest at exactly the moment it was added to help: a cold process under load.",
        fix:
          "Share the in-flight promise instead of a boolean: `let inflight: Promise<Rates> | null`, and `return inflight ?? (inflight = fetchRates(base))`. A `!` on a field that the code path can prove is null is the tell.",
      },
      {
        family: "failure",
        title: "`refreshing` is never reset on a rejection",
        signal: "silent",
        severity: "blocker",
        body:
          "There is no `try/finally`. If `fetchRates` rejects, `refreshing` stays `true` for the life of the process and the `if (refreshing)` branch short-circuits every future call, so no further fetch is ever attempted. The service then serves the last successful table forever — or, on a cold start, throws forever — and the only fix is a restart. This is the defect the cold-start crash hides: the crash is loud and gets fixed first, and the obvious fix (seed `cached` with a default) converts this from a crash into a silent, permanently stale rate table.",
        fix: "`try { ... } finally { refreshing = false }`, and treat 'refresh has been failing for N minutes' as an alert, not a log line.",
      },
      {
        family: "time",
        title: "`asOf` measures rate age, not cache age",
        signal: "silent",
        severity: "major",
        body:
          "`asOf` is documented as when the rates were *struck*, which is the issuer's timestamp, not when we fetched them. `Date.now() - cached.asOf < TTL_MS` therefore asks how old the quote is, not how old our copy is. A gateway that returns rates struck at the last market fix hands us a payload whose `asOf` is already older than 60 seconds, the freshness test fails on every call, and the cache — the entire point of the change — never serves a single hit while looking like it is working.",
        fix: "Record `fetchedAt = Date.now()` when the response lands and expire on that; keep `asOf` for display only.",
      },
      {
        family: "contract",
        title: "`convert` still silently falls back to a rate of 1",
        signal: "silent",
        severity: "blocker",
        body:
          "Unchanged by this diff and therefore easy to scroll past: `rates.quotes[to] ?? 1` treats an unknown currency as parity. An order in a currency the table does not carry — a newly supported market, a currency the gateway dropped, or the wrong-base table above — is charged its numeric amount in the base currency. 5,000 JPY becomes 5,000 USD. The change makes this worse by making a stale or wrong-base table much more likely to be what `convert` is handed.",
        fix: "Throw on an unknown currency. A missing exchange rate has no safe default.",
      },
    ],
  },
  {
    id: 39,
    slug: "go-rate-table",
    lang: "Go",
    level: "Standard",
    title: "Background-refreshed FX table",
    shape: "function",
    code: t(s39),
    brief:
      "One `Table` per process. `Start` runs at boot; handlers call `Quote` on every order.",
    hintRegion:
      "`Quote` copies one thing out from under the read lock. `refresh` writes to the thing it copied.",
    hintFamily: "Shared state, Time & concurrency, Failure surface.",
    defects: [
      {
        family: "state",
        title: "The map reference escapes the read lock",
        signal: "loud",
        severity: "blocker",
        body:
          "`quotes := t.quotes` copies the map *header*, not the map, and the lock is released immediately after. `refresh` then writes into that same map under the write lock — and a map read concurrent with a map write is not a data race Go tolerates: the runtime detects it and aborts the process with `fatal error: concurrent map read and map write`, which no `recover` can catch. A crash loop on every refresh tick, under load, with a stack trace in the runtime rather than in this file.",
        fix:
          "Either read the value while still holding the lock (`rate, ok := t.quotes[code]` before `RUnlock`), or have `refresh` build a new map and swap the field, making the old map immutable once published.",
      },
      {
        family: "state",
        title: "`refresh` merges instead of replacing",
        signal: "silent",
        severity: "major",
        body:
          "The loop copies the fetched rates *into* the existing map, so a code that has disappeared upstream — a delisted currency, a pair the provider stopped quoting, a typo removed from the source data — keeps its last known rate forever. `Quote` returns it with `ok == true` and no indication that the number is from whenever it was last quoted, which could be months. The map also only ever grows.",
        fix: "Build a fresh map and assign it, so a code absent from the fetch is absent from the table.",
      },
      {
        family: "failure",
        title: "A failed refresh turns every request into a fetch",
        signal: "silent",
        severity: "blocker",
        body:
          "`refresh` logs the error and returns without touching `fetched`, so the table stays stale and `Quote`'s `stale` test is true for every subsequent request. Each one then calls `t.fetch` inline and pays its full latency. A provider outage is therefore amplified from one request per TTL into one per *order*, aimed at a dependency that is already failing, while every handler blocks on it. The log line is one per request, so the logs are also unusable for the duration.",
        fix:
          "Back off on failure (record the attempt time and refuse to retry inside a cooldown), cap it with a circuit breaker, and serve the stale value while it is open.",
      },
      {
        family: "time",
        title: "No single flight, and the cold table is stale by definition",
        signal: "silent",
        severity: "major",
        body:
          "`fetched` is the zero `time.Time`, so `time.Since(t.fetched) > t.ttl` is true for every request that arrives before the first tick — and the first tick is a whole TTL after `Start`. Every one of those requests calls `refresh` concurrently, so a deploy under load opens N simultaneous connections to the rate provider for the same data. The same herd forms after every expiry, because nothing coordinates the refreshers.",
        fix:
          "Refresh once synchronously in `New` or at the top of `Start`, and gate inline refreshes through a `golang.org/x/sync/singleflight` group.",
      },
      {
        family: "contract",
        title: "`Quote` cannot tell the caller the rate is stale",
        signal: "silent",
        severity: "major",
        body:
          "The doc comment promises the table is refreshed rather than serving an out-of-date rate, but when the refresh fails `Quote` returns the old value with `ok == true` and no age. A caller pricing an order has no way to decide that a rate from four hours ago is not good enough to commit to, because the signature does not carry the one fact that would let it. `Start` also leaks: the ticker is never stopped and the goroutine never selects on `ctx.Done()`, so the boot context is captured forever and a cancelled one makes every refresh fail instantly.",
        fix:
          "Return the rate's age (or an error when it exceeds a maximum), and give `Start` a `select` on `ctx.Done()` with `defer ticker.Stop()`.",
      },
    ],
  },
  {
    id: 40,
    slug: "usage-rollup",
    lang: "Java",
    level: "Hard",
    title: "Metered usage rollup",
    shape: "function",
    code: t(s40),
    brief:
      "This is what the invoices are computed from. Request threads call `record`; the scheduler calls `flush`.",
    hintRegion:
      "Two fields are shared across threads and neither is declared for it. Then read every use of a date.",
    hintFamily: "Shared state, Time & concurrency, Failure surface.",
    defects: [
      {
        family: "state",
        title: "A plain `HashMap` shared by request threads and the flusher",
        signal: "silent",
        severity: "blocker",
        body:
          "`pending` is a `java.util.HashMap`. Request threads call `merge` on it concurrently and the flusher iterates and removes from it. Concurrent `merge` during a resize loses entries outright or corrupts a bucket chain; iteration concurrent with a write throws `ConcurrentModificationException` *sometimes* and silently skips entries the rest of the time. Metered usage that is lost is revenue never billed, and there is no second copy anywhere that says it existed.",
        fix:
          "`ConcurrentHashMap` with `merge`, or an append-only queue that only the flusher drains. Either way the aggregation has to be the single writer's job.",
      },
      {
        family: "state",
        title: "`draining` is not `volatile`, and the guard drops events",
        signal: "silent",
        severity: "blocker",
        body:
          "One field with two defects that conceal each other. `draining` is written by the flusher thread and read by request threads with no `volatile` and no lock, so there is no happens-before edge: the JIT may hoist the read out of the hot path and a request thread can go indefinitely without ever observing `true`. That is why the *second* defect almost never shows in testing — when the guard does fire, `record` simply `return`s, silently discarding the event instead of queueing it. Make the field `volatile`, which is the obvious fix and the one a reviewer reaches for, and you convert an invisible visibility bug into a reliable, measurable hole in the billing data every five minutes.",
        fix:
          "Delete the flag. Correct publication is not the point — an event must never be dropped, so the map has to accept writes during a flush (see above) rather than being fenced off.",
      },
      {
        family: "time",
        title: "The event's day and `today` come from different clocks",
        signal: "silent",
        severity: "blocker",
        body:
          "`at.toLocalDate()` takes the day from a `LocalDateTime` the caller built in whatever zone it was working in, while `today` is `LocalDate.now()` in the *JVM default* zone. On a host running UTC, usage at 18:00 America/Los_Angeles is already tomorrow, so it lands in the next day's bucket and is flushed a day early into a period the invoice has closed. The two zones agree for most of each day, so the daily totals are right most of the time and wrong near the boundary — which is when the batch jobs run.",
        fix:
          "Take an `Instant` from the caller and convert it once, explicitly, in the zone the contract bills in. Never call a `now()` that reads the default zone.",
      },
      {
        family: "time",
        title: "The last day of a period is never flushed",
        signal: "silent",
        severity: "major",
        body:
          "`flush` only batches days strictly before `today`, and `today` is only advanced when a flush runs. A customer whose usage stops — the end of a trial, a cancelled account, the last day of a billing period for a low-traffic tenant — has a bucket that no flush ever considers complete until some later tick happens to see a new date. The invoice run reads the warehouse, not `pending`, so that day is simply absent from the bill, and a missing day looks exactly like a day with no usage.",
        fix:
          "Flush a day once the wall clock passes its end plus a grace window, and flush on shutdown with a registered hook.",
      },
      {
        family: "time",
        title: "`billableHours` throws the zone away before measuring",
        signal: "silent",
        severity: "major",
        body:
          "`atStartOfDay(zone)` correctly resolves the instant, and `toLocalDateTime()` immediately discards the offset, so `Duration.between` measures wall-clock arithmetic. A period containing a spring-forward transition reports 24 hours for a day that had 23, and an autumn fall-back reports 24 for a day that had 25. Every customer in a DST zone is billed for an hour that did not exist, twice a year, on an invoice line that is plausible to the hour.",
        fix:
          "`Duration.between(from.atStartOfDay(zone), to.atStartOfDay(zone))` on the `ZonedDateTime`s, without the conversion — and decide whether a billing 'day' is a calendar day or 24 hours, because they are not the same thing.",
      },
      {
        family: "failure",
        title: "One exception stops all flushing, permanently and silently",
        signal: "silent",
        severity: "blocker",
        body:
          "`scheduleAtFixedRate` cancels the schedule the first time the task throws, and the `ScheduledFuture` is discarded, so nothing logs it and nothing restarts it. The intermittent `ConcurrentModificationException` from the first defect is exactly the trigger: one occurrence and the process stops flushing for the rest of its life while `record` keeps filling a map nobody drains — an unbounded memory leak whose contents are the unbilled revenue. And `warehouse.write(batch)` is not transactional with the `pending.remove` loop, so a write that throws halfway has already committed some rows while `pending` still holds all of them, and a write that succeeds followed by a crash before the removes double-counts them on the next flush.",
        fix:
          "Wrap the task body in `try/catch(Throwable)` and log, keep the future and check it, and make the drain idempotent: remove from `pending` only what the warehouse confirms, keyed so a replay is a no-op.",
      },
    ],
  },
  {
    id: 41,
    slug: "claim-jobs",
    lang: "SQL",
    level: "Standard",
    title: "Claim the next batch of jobs",
    shape: "diff",
    code: t(s41),
    brief:
      "Twelve workers run this query in a loop. The change adds locking, priority and an attempt counter.",
    hintRegion:
      "The CTE selects rows and the UPDATE matches them by id. Ask what a second worker running this at the same instant sees.",
    hintFamily: "Shared state, Time & concurrency, Contract.",
    defects: [
      {
        family: "state",
        title: "No `FOR UPDATE SKIP LOCKED` — every job is claimed twice",
        signal: "silent",
        severity: "blocker",
        body:
          "The CTE is a plain `SELECT`, so under READ COMMITTED two workers running this at the same moment both see the same ten `queued` rows. The second `UPDATE` blocks on the first's row locks, and when it wakes it re-evaluates its own `WHERE` — which is `id IN (SELECT id FROM next)`, an id list that is still satisfied no matter what the status now says. So it claims the same ten rows, sets `locked_by` to itself, and `RETURNING` hands the payloads to a second worker. Every job runs twice, both workers succeed, and with twelve workers the multiplier is worse than two.",
        fix:
          "`SELECT id ... FOR UPDATE SKIP LOCKED` in the CTE. The `SKIP LOCKED` is what makes it a queue rather than a convoy.",
      },
      {
        family: "time",
        title: "The stale-lock reclaim is dead code",
        signal: "silent",
        severity: "blocker",
        body:
          "The reclaim clause only matches rows where `status = 'queued'`, and claiming a row sets `status = 'running'`. So a job whose worker was OOM-killed sits at `running` with a `locked_at` from an hour ago and is never selected again by anything: the clause that exists to recover it can never see it. Jobs leak out of the queue permanently, one per worker death. This is invisible until the race above is fixed — while every job is being claimed repeatedly, something always picks the work up anyway, so nothing appears stuck. Fixing the locking is what starts the stalls.",
        fix:
          "`WHERE status = 'queued' OR (status = 'running' AND locked_at < NOW() - INTERVAL '5 minutes')`, and make the reclaim visible: count it, alert on it, and cap it with `attempts`.",
      },
      {
        family: "contract",
        title: "`ORDER BY priority DESC` puts NULLs first",
        signal: "silent",
        severity: "major",
        body:
          "In Postgres `DESC` implies `NULLS FIRST`. Every row that existed before this change has a NULL `priority` until a backfill runs, so the new ordering is inverted at exactly the moment it is deployed: the entire unprioritised backlog sorts ahead of the explicitly high-priority work the change was written to expedite. The query is correct, the plan is fine, and the feature does the opposite of what it says.",
        fix:
          "`ORDER BY priority DESC NULLS LAST, created_at`, and give the column a `NOT NULL DEFAULT 0` so the ambiguity cannot arise.",
      },
      {
        family: "boundary",
        title: "Four new columns, no migration, and no attempt cap",
        signal: "mixed",
        severity: "major",
        body:
          "The change that is not in the diff. `locked_at`, `locked_by`, `priority` and `attempts` all appear for the first time in these lines, and no migration accompanies them — so this deploys as an error on every worker's first query, and the queue stops. `attempts = attempts + 1` is also incremented but never read: nothing caps it, so a job that crashes its worker on every attempt is retried until someone notices, and with the reclaim above fixed that is forever rather than never. Nor does anything in this change move a job out of `running` on success or failure.",
        fix:
          "Ship the migration in the same change, with defaults and an index on `(status, priority DESC NULLS LAST, created_at)`; add `AND attempts < :max` to the claim and a dead-letter path for what exceeds it.",
      },
    ],
  },
  {
    id: 42,
    slug: "api-rate-limiter",
    lang: "JavaScript",
    level: "Standard",
    title: "Per-key API rate limiter",
    shape: "function",
    code: t(s42),
    brief:
      "`allow` is called on every public API request. `key` is the caller's API key, taken from the request header.",
    hintRegion:
      "`buckets` is an object literal and `key` comes from a header. Then ask what 'rolling' means in the docstring.",
    hintFamily: "Shared state, Time & concurrency, Silent coercion.",
    defects: [
      {
        family: "state",
        title: "A key of `__proto__` poisons every object in the process",
        signal: "silent",
        severity: "blocker",
        body:
          "`buckets` is `{}`, so it inherits from `Object.prototype` and property lookup finds inherited names. A request whose API key is `__proto__` makes `buckets[key]` resolve to `Object.prototype`: `bucket.start` is `undefined`, `now - undefined` is `NaN`, `NaN > windowMs` is `false`, so the reset branch never runs and `bucket.count++` writes `NaN` onto `Object.prototype`. Every object in the process now has an enumerable `count` property, and every `for...in` anywhere in the codebase visits it. `NaN <= max` is `false`, so that key is also limited to zero requests forever. `constructor`, `toString` and `valueOf` all behave the same way, and the input is attacker-controlled.",
        fix:
          "`const buckets = new Map()` — or `Object.create(null)` at minimum — and validate the key against the format your keys actually have before it is used as a property name.",
      },
      {
        family: "time",
        title: "A fixed window, documented as rolling, allows 2x the limit",
        signal: "silent",
        severity: "major",
        body:
          "The docstring says rolling; the code resets the whole bucket once `windowMs` has elapsed since its start. A caller can send `max` requests in the last millisecond of one window and `max` more in the first millisecond of the next, so the real ceiling across any window-sized interval is `2 x max`. The published limit is a number the implementation cannot hold, and the caller most likely to find that out is the one hammering you.",
        fix:
          "A sliding window (keep timestamps, or two weighted counters) or a token bucket with a refill rate — and then make the documented number the one the code enforces.",
      },
      {
        family: "coercion",
        title: "`for...in` walks the prototype chain",
        signal: "mixed",
        severity: "major",
        body:
          "`sweep` iterates with `for...in`, which visits inherited enumerable properties. Once the defect above has put `count` on `Object.prototype`, `sweep` visits it, `buckets[\"count\"]` is `NaN`, and `NaN.start` throws — inside a timer callback, where the rejection is swallowed and the timer never fires again. The sweeper stops silently and the bucket table grows without bound from then on. Separately, `for...in` visits integer-like keys in ascending numeric order rather than insertion order, so numeric API keys are swept in an order the code does not look like it chose.",
        fix: "`Object.entries` / `Map#forEach`, and a `try/catch` around the body of any timer callback.",
      },
      {
        family: "time",
        title: "The window is measured on the wall clock",
        signal: "silent",
        severity: "major",
        body:
          "`Date.now()` is subject to NTP correction, a manual clock change and a VM's clock resync after a live migration. A backwards step larger than `windowMs` makes `now - bucket.start` negative, so `> windowMs` is false and no bucket in the process ever resets again: every key is stuck at whatever count it had reached, and every caller over the limit stays over it until a full window of corrected time has passed. `retryAfter` returns a negative number in the same situation, which serialises into a `Retry-After` header clients handle in whatever way they feel like.",
        fix:
          "Measure elapsed time from a monotonic source (`performance.now()`, or `process.hrtime.bigint()`), and clamp `retryAfter` to `>= 0`.",
      },
      {
        family: "state",
        title: "One shared table, per-call limits",
        signal: "silent",
        severity: "major",
        body:
          "`max` and `windowMs` are arguments, but `buckets` is module state with no record of which limit produced an entry. Two call sites with different limits — a 100/minute public route and a 10/minute export route — share one bucket per key: whichever one created the bucket set the window boundary, each then compares the shared count against its own `max`, and the export route's budget is consumed by public traffic. The signature promises per-call configuration the storage cannot represent.",
        fix:
          "Key on `(limit, key)`, or pass a limiter instance configured once per route rather than the limits per call.",
      },
    ],
  },
  {
    id: 43,
    slug: "digest-builder",
    lang: "Python",
    level: "Hard",
    title: "Daily digest builder",
    shape: "function",
    code: t(s43),
    brief:
      "The nightly job constructs one builder per account and sends whatever `build` returns. Accounts are in every timezone.",
    hintRegion:
      "One defect is on line 15, before any method. The `sections is None` guard is correct — ask what it does not cover.",
    hintFamily: "Shared state, Time & concurrency, Boundaries.",
    defects: [
      {
        family: "state",
        title: "`footer` is a class attribute, and the digest leaks across accounts",
        signal: "silent",
        severity: "blocker",
        body:
          "`footer = []` is defined on the class, and `self.footer.append(...)` resolves the attribute on the class and mutates that list in place — no instance attribute is ever created. Every `DigestBuilder` in the process shares one list, so the second account's digest ends with two footer lines, the five-hundredth ends with five hundred, and each one names another customer's email address. A cross-tenant data leak, in an email, that a unit test building a single digest cannot see. The `if sections is None` guard three lines earlier is what makes a reviewer decide this author knows about mutable shared defaults.",
        fix:
          "Build the footer in `__init__` as `self.footer = []`, or better, return a fresh list from a method. A mutable class attribute is shared state whether it was meant to be or not.",
      },
      {
        family: "state",
        title: "`sections` is mutated when the caller does pass one",
        signal: "silent",
        severity: "major",
        body:
          "The `is None` guard protects the default but not the argument. A caller that builds a list of shared header blocks once and passes it for every account has that list appended to on every call, so account N's digest contains every event and footer from accounts 1..N-1. This is also what conceals the defect above: while the caller's list is growing, the footer growing too is indistinguishable from it, and fixing this one is what isolates the class attribute as a separate cause.",
        fix: "`sections = list(sections) if sections else []` — copy on the way in, and say in the docstring that the argument is not modified.",
      },
      {
        family: "time",
        title: "A naive local `now` against naive UTC timestamps",
        signal: "silent",
        severity: "major",
        body:
          "`datetime.now()` is the server's local wall clock with no tzinfo, and `event.created_at` is naive **UTC** — the docstring says so, and `_render` confirms it by localizing to UTC. The comparison does not raise, because both sides are naive; it is simply wrong by the host's UTC offset. On a host in UTC-7, `since` is seven hours later than intended and the digest silently omits the oldest seven hours of the day it claims to cover. In CI, where the host is UTC, the window is exactly right and the defect does not exist.",
        fix:
          "`datetime.now(timezone.utc)` and make every timestamp in the system aware. If timestamps must be naive at the storage layer, convert once at the boundary and never compare across the two kinds.",
      },
      {
        family: "time",
        title: "`localize` applied to a UTC instant in `next_run`",
        signal: "silent",
        severity: "major",
        body:
          "`datetime.utcnow()` returns a naive datetime holding UTC wall time, and `self.tz.localize(now)` *asserts* that the naive value is already local time in `self.tz`. So a UTC instant is relabelled as Tokyo wall time, nine hours off, and the '07:00 local' the method computes is 07:00 on the wrong day for anyone far enough east or west. `build` defaults to `datetime.now()` while `next_run` defaults to `datetime.utcnow()`, so the two methods of the same class do not even agree on what `now` means.",
        fix: "`datetime.now(pytz.utc).astimezone(self.tz)` — convert, never `localize`, a value that is already an instant.",
      },
      {
        family: "time",
        title: "`.replace()` on a pytz datetime keeps the old offset",
        signal: "silent",
        severity: "major",
        body:
          "This is pytz's documented trap: a localized datetime carries the offset that was in force at *that* moment, and `.replace(hour=7, ...)` changes the fields while keeping that tzinfo. Across a DST boundary the result is tagged with yesterday's offset, so `astimezone(pytz.utc)` produces an instant an hour away from 07:00 local and the digest goes out at 06:00 or 08:00 for the account. `.replace` also leaves `microsecond` alone, so the `<=` comparison can decide 'already past' on a sub-second difference.",
        fix:
          "`self.tz.normalize(local)` after any arithmetic or `replace`, or move to `zoneinfo`, where `replace(tzinfo=...)` resolves the offset correctly.",
      },
      {
        family: "boundary",
        title: "The window has no upper bound",
        signal: "silent",
        severity: "minor",
        body:
          "`e.created_at > since` filters the old end and nothing filters the new one. An event with a timestamp in the future — clock skew on a producing service, a scheduled item stored with its target time, a timezone bug upstream — is newer than `since` on every run, so it appears in that account's digest every single day until the future catches up with it.",
        fix: "`since < e.created_at <= now`, and reject a `created_at` beyond a small tolerance at the write path.",
      },
    ],
  },
  {
    id: 44,
    slug: "editor-autosave",
    lang: "React",
    level: "Standard",
    title: "Autosave in a document editor",
    shape: "diff",
    code: t(s44),
    brief:
      "Users lose work when they close the tab. This change saves the document every three seconds while it is dirty.",
    hintRegion:
      "The author used a ref for `dirty` and not for `body`. Then ask what happens between the `await` and the line after it.",
    hintFamily: "Shared state, Time & concurrency, Failure surface.",
    defects: [
      {
        family: "state",
        title: "The interval saves the document the user started from",
        signal: "silent",
        severity: "blocker",
        body:
          "The effect has `[]` as its dependency list, so the callback passed to `setInterval` closes over `body` from the first render forever — the value of `initial`. `dirty.current` flips true on the first keystroke, the PUT fires, and it sends the original text. The server copy is overwritten with the pre-edit document, the request returns 200, and the UI updates to 'saved 14:32'. Everything the user typed is destroyed, and the interface confirms it was saved. Note that the author reached for `useRef` for `dirty` precisely because refs escape the closure — and then read `body` from the closure anyway.",
        fix:
          "Hold the text in a ref alongside the state (`bodyRef.current = e.target.value`) and read the ref inside the interval, or list `body` in the dependencies and accept the interval being recreated per keystroke.",
      },
      {
        family: "state",
        title: "`dirty.current = false` after the await loses edits",
        signal: "silent",
        severity: "blocker",
        body:
          "The flag is read at the top of the callback and cleared *after* the PUT resolves. Every keystroke that lands while the request is in flight sets it to true, and the completion then clears it — so those characters are marked clean and will never be sent. A slow network widens the window; a 500 ms round trip means roughly half a second of typing is silently dropped on every save cycle. This is completely hidden while the defect above is present, because nothing the user types is ever sent at all. Fixing the stale closure is what starts losing edits.",
        fix:
          "Snapshot the body and clear the flag *before* the request, and re-set it if the request fails. Compare a saved-version marker rather than a boolean.",
      },
      {
        family: "failure",
        title: "The fetch result is never checked, and a rejection is swallowed",
        signal: "silent",
        severity: "blocker",
        body:
          "`await fetch(...)` is not inspected, so a 401 after a session expiry, a 409 from a concurrent editor and a 413 on a large document all fall straight through to `setSavedAt(Date.now())` and the label says 'saved'. And a network failure *rejects*: the async callback passed to `setInterval` returns a promise nobody holds, so the rejection is an unhandled promise rejection that logs nothing useful to the user, `dirty.current` is never cleared, and the UI still shows the last successful time — steadily older while the user keeps typing into a document that is not being saved.",
        fix:
          "Check `res.ok`, wrap in `try/catch`, and surface a real state: 'saving', 'saved at T', 'failed — retrying'. Never report success on an unexamined response.",
      },
      {
        family: "time",
        title: "`setInterval` does not wait for the previous save",
        signal: "silent",
        severity: "major",
        body:
          "The interval fires every three seconds regardless of whether the last PUT has returned. A save slower than that overlaps the next one, and two in-flight PUTs can land in either order, so an older body can be written after a newer one. With no version or sequence number on the request the server cannot detect it and last-write-wins does the wrong thing.",
        fix:
          "Chain with `setTimeout` after each save completes, and send a version the server can reject with a 409 on a stale write.",
      },
      {
        family: "contract",
        title: "Nothing resets on a new document, and nothing saves on unmount",
        signal: "silent",
        severity: "blocker",
        body:
          "Outside the changed lines, and the reason a diff review is worth paying for. `docId` is read from the closure of an effect with no dependencies, so navigating from document A to document B — without a `key` forcing a remount — keeps A's `body` in state *and* keeps PUTing to A's id: edits to B are written over A. `body` is also initialised from `initial` only on mount, so a changed `initial` prop is ignored. And the cleanup only clears the interval: the up-to-three seconds of typing since the last tick is discarded on every navigation and tab close, which is the exact problem this change was written to solve.",
        fix:
          "Put `docId` and `body` in the dependency list (or key the component on `docId`), and flush a final save in the cleanup and on `visibilitychange`.",
      },
    ],
  },
  {
    id: 45,
    slug: "token-source",
    lang: "TypeScript",
    level: "Hard",
    title: "Shared service token with single-flight mint",
    shape: "function",
    code: t(s45),
    brief:
      "One instance per process, on the path of every outbound call. Tokens live an hour.",
    hintRegion:
      "`inflight` is assigned in exactly one place. Find every path that should clear it and count how many do.",
    hintFamily: "Shared state, Failure surface, Time & concurrency.",
    defects: [
      {
        family: "state",
        title: "`inflight` is never cleared, so the first token is the only token",
        signal: "silent",
        severity: "blocker",
        body:
          "Nothing ever sets `inflight` back to `null`. The first mint's promise is memoised for the life of the process, so once the token passes its expiry the freshness test fails, `if (!this.inflight)` is false, and `await this.inflight` resolves the *original, expired* token — forever. Every outbound call then presents an expired credential and every downstream starts returning 401 about an hour after each deploy, from a process that is otherwise healthy. No test run lasts longer than a token lifetime, so this is invisible until it is in production, at which point it looks like an identity-provider problem.",
        fix: "`try { return await this.inflight } finally { this.inflight = null }` — and clear it in `invalidate` too.",
      },
      {
        family: "failure",
        title: "A rejected mint is cached and replayed forever",
        signal: "silent",
        severity: "blocker",
        body:
          "If `mint()` rejects, the rejected promise stays in `inflight` and every subsequent caller awaits the same one, so a single transient failure at boot — a DNS blip, the identity provider restarting — permanently poisons the token source. Worse for diagnosis: each caller receives the *original* error, so the message, the stack and any correlation id point at a request that completed minutes or hours ago, and the logs show an error that cannot be correlated with anything happening now. This is the defect that gets found in staging, because a mint failure is easy to inject — and clearing `inflight` only on rejection leaves the defect above completely intact, because the success path still never clears it.",
        fix:
          "The same `finally`. One `finally` fixes both; a `catch` fixes only the one you were looking at.",
      },
      {
        family: "state",
        title: "`invalidate()` does not clear `inflight`",
        signal: "silent",
        severity: "major",
        body:
          "`invalidate` is the 401 handler: its whole purpose is to force a fresh mint. It clears `token` and leaves `inflight`, so the next `get()` skips the freshness test, finds `inflight` truthy, and returns the very token the downstream just rejected. The caller retries, gets another 401, invalidates again, and receives the same token — a tight loop against the downstream with a rejected credential, which is how a single revoked key becomes a rate-limit ban.",
        fix: "`invalidate() { this.token = null; this.inflight = null; }`, and cap the caller's retry at one.",
      },
      {
        family: "state",
        title: "A late joiner re-caches a token that was already rejected",
        signal: "silent",
        severity: "major",
        body:
          "`this.token = token` runs unconditionally after the await, for every caller. A caller that joined a mint started *before* an `invalidate()` completes afterwards and writes that token back into `this.token`, resurrecting the credential the 401 handler had just discarded. Concurrency turns `invalidate` from a guarantee into a suggestion, and which of the two effects wins depends on request timing.",
        fix:
          "Tag each mint with a generation counter, bump it in `invalidate`, and only store the result if the generation still matches.",
      },
      {
        family: "time",
        title: "Expiry is checked against the local wall clock",
        signal: "silent",
        severity: "major",
        body:
          "`clock: Clock = Date` means `Date.now()`, the local wall clock, compared against an `expiresAt` that came from the issuer. If that value was derived from a JWT `exp` claim it is on the *issuer's* clock, and the 30-second skew budget is applied in one direction only: a host running a minute behind considers an expired token live and presents it, while a host running ahead merely mints early. Clock drift of a minute is ordinary on a VM that has not resynced, and there is nothing in the type to say which clock `expiresAt` belongs to. Nothing validates the minted token either, so a `mint` that returns an `expires_in` misread as seconds-instead-of-milliseconds produces an already-expired token — which, combined with the first defect, is pinned in place forever.",
        fix:
          "Compute `expiresAt` from our own clock at the moment the response lands (`now + expires_in`), give the skew a realistic margin, and reject a minted token that is already past expiry.",
      },
    ],
  },
];
